// Copyright (c) 2011,cd-team.org.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
#pragma once
#include <string>
#include <sstream>
using namespace std;
class HtmlHelper
{
	static const string _html_index_tmpl;
	static const string _html_tmpl;
	static const string _content_hold;
	static const string _title_hold;
	static const string _link_keylist_hold;
	static const string _link_trace_hold;
private:
	static void PrintHostInfo(stringstream& ss);
	static void PrintAllTickets(stringstream& ss);
	static string MakeTableTitleHtml(const string& title);
	static string MakeTableTwoColumnRow(const string& name,const string& desc);
	static string MakeTableTwoTitleRow(const string& s1,const string& s2);
	static string MakeTableThreeColumnRow(const string& s1,const string& s2,const string& s3);
	static string MakeTableThreeTitleRow(const string& s1,const string& s2,const string& s3);
	static void HtmlHelper::Print4ServerInfo(stringstream& ss);
	static void HtmlHelper::Print4sServerInfo(stringstream& ss);
public:
	static string GetHostHtmlInfo();
	static string GetTraceHtml();
	static string GetKeyListHtml();
	static void InitUrls();

	static string admin_index_url;
	static string admin_base_url;
	static string key_man_url;
	static string key_trace_url;
};
