// Copyright (c) 2011,cd-team.org.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
#pragma once
#include <plist/plist++.h>
#include <vector>
using namespace std;
struct Ticket;

typedef enum HOST_PLIST_RESULT
{
	RESULT_OK=1,
	RESULT_SESSION_EPRIED=2,
	RESULT_COMMAND_FAILED=4,
	RESULT_ASSISTANT_LOADED=8,
	RESULT_ASSISTANT_CREATE=16,
	RESULT_ADD_VIEWS=32
};

typedef enum FIX_PLIST_RESULT
{
	FIX_RESULT_NOKEY=-2,
	FIX_RESULT_INVALID_KEY=-1,
	FIX_RESULT_FAIL=0,
	FIX_RESULT_SUCCESS=1
};

HOST_PLIST_RESULT  check_host_plist_result(const char* plistData,const size_t dataLen,Ticket* pTicket);
FIX_PLIST_RESULT fix_plist_xml(const char* plistData,const size_t& dataLen,vector<char>&fixOut,Ticket* pTicket,bool iphone4s,bool& processed,char** pplistXML=NULL);
FIX_PLIST_RESULT process_iphone4_plist(plist_t plist,bool& processed,Ticket* pTicket,char** pplistXML);
FIX_PLIST_RESULT process_iphone4s_plist(plist_t plist,bool& processed,Ticket* pTicket,char** pplistXML=0);
char* plist_bin_to_xml(const char* plistData,const size_t& dataLen);
bool plist_xml_to_bin(const char* plistxml,char** ppfixdata,size_t& nLen);